# Generated by Django 3.1.5 on 2021-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botspecies',
            name='parts_value',
            field=models.IntegerField(default=10),
        ),
    ]
