# Generated by Django 3.1.5 on 2021-01-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210122_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='loadout',
        ),
        migrations.DeleteModel(
            name='LoadoutEntry',
        ),
    ]
