# Generated by Django 3.1.5 on 2021-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210123_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movesetentry',
            options={'verbose_name_plural': 'moveset'},
        ),
        migrations.AddConstraint(
            model_name='movesetentry',
            constraint=models.UniqueConstraint(fields=('bot_species', 'technique'), name='unique_species_technique'),
        ),
    ]
